// Autogenerated by Thrift Compiler (0.10.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package cli_service

import (
	"bytes"
	"fmt"
	"git.apache.org/thrift.git/lib/go/thrift"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = bytes.Equal

var PRIMITIVE_TYPES map[TTypeId]struct{}
var COMPLEX_TYPES map[TTypeId]struct{}
var COLLECTION_TYPES map[TTypeId]struct{}
var TYPE_NAMES map[TTypeId]string

func init() {
PRIMITIVE_TYPES = map[TTypeId]struct{}{
    0: struct{}{},
    1: struct{}{},
    2: struct{}{},
    3: struct{}{},
    4: struct{}{},
    5: struct{}{},
    6: struct{}{},
    7: struct{}{},
    8: struct{}{},
    9: struct{}{},
}

COMPLEX_TYPES = map[TTypeId]struct{}{
    10: struct{}{},
    11: struct{}{},
    12: struct{}{},
    13: struct{}{},
    14: struct{}{},
}

COLLECTION_TYPES = map[TTypeId]struct{}{
    10: struct{}{},
    11: struct{}{},
}

TYPE_NAMES = map[TTypeId]string{
    0: "BOOLEAN",
    1: "TINYINT",
    2: "SMALLINT",
    3: "INT",
    4: "BIGINT",
    5: "FLOAT",
    6: "DOUBLE",
    7: "STRING",
    8: "TIMESTAMP",
    9: "BINARY",
    10: "ARRAY",
    11: "MAP",
    12: "STRUCT",
    13: "UNIONTYPE",
}

}

